const styles = {
   fontFamily: {
    property: 'fontFamily',
    examples: [
      'Verdana,Geneva,sans-serif',
      'Helvetica,Arial,sans-serif',
      '"Lucida Sans Unicode", "Lucida Grande", sans-serif',
      '"Trebuchet MS", Helvetica, sans-serif',
      'Georgia,Utopia,Charter,serif',
      '"Times New Roman",Times,serif',
      '"Courier New",Courier,monospace',
      '"Palatino Linotype", "Book Antiqua", Palatino, serif',
      '"Comic Sans MS", cursive, sans-serif',
      'Impact, Charcoal, sans-serif'
    ],
    exampleText: "The quick brown fox jumps over the lazy dog"
  },
  borderStyle: {
    property: 'borderStyle',
    defaultStyles: {
      borderWidth: '5px',
      borderColor: 'plum',
      color: 'white'
    },
    examples: [
      'solid',
      'double',
      'dotted',
      'dashed',
      'ridge',
      'inset',
      'outset',
      'groove'
    ]
  },
  borderRadius: {
    property: 'borderRadius',
    defaultStyles: {
      width: '100px',
      height: '100px',
      backgroundColor: 'MediumOrchid',
      color: 'transparent'
    },
    examples: [
      '5px',
      '25px',
      '50%'
    ]
  },
  boxShadow: {
    property: 'boxShadow',
    defaultStyles: {
      width: '100px',
      height: '100px'
    },
    examples: [
      '0 0 5px #888',
      '5px 5px 0 #888',
      '5px 5px 5px #888',
      '0 0 5px 2px magenta',
      'inset 0 0 8px goldenrod'
    ]
  },
  textShadow: {
    property: 'textShadow',
    defaultStyles: {
      fontSize: '36px',
      fontWeight: 'bold',
      color: 'lightgrey',
      fontFamily: 'Arial'
    },
    examples: [
      '2px 2px 2px #888',
      '1px 1px 0 black',
      '2px 2px 0px white, 4px 4px 0px #888',
      '0px 0px 2px magenta'
    ]
  },
  fontStyle: {
    property: 'fontStyle',
    defaultStyles: {},
    examples: [
      'normal',
      'italic'
    ]
  },
  backgroundColor: {
    property: 'backgroundColor',
    defaultStyles: {
      width: '100px',
      height: '25px',
      color: 'transparent'
    },
    examples: [
      "LightPink",
      "Pink",
      "Crimson",
      "LavenderBlush",
      "PaleVioletRed",
      "HotPink",
      "DeepPink",
      "MediumVioletRed",
      "Orchid",
      "Thistle",
      "Plum",
      "Violet",
      "Magenta",
      "Fuchsia",
      "DarkMagenta",
      "Purple",
      "MediumOrchid",
      "DarkViolet",
      "DarkOrchid",
      "Indigo",
      "BlueViolet",
      "MediumPurple",
      "MediumSlateBlue",
      "SlateBlue",
      "DarkSlateBlue",
      "Lavender",
      "GhostWhite",
      "Blue",
      "MediumBlue",
      "MidnightBlue",
      "DarkBlue",
      "Navy",
      "RoyalBlue",
      "CornflowerBlue",
      "LightSteelBlue",
      "LightSlateGray",
      "SlateGray",
      "DodgerBlue",
      "AliceBlue",
      "SteelBlue",
      "LightSkyBlue",
      "SkyBlue",
      "DeepSkyBlue",
      "LightBlue",
      "PowderBlue",
      "CadetBlue",
      "Azure",
      "LightCyan",
      "PaleTurquoise",
      "Cyan",
      "Aqua",
      "DarkTurquoise",
      "DarkSlateGray",
      "DarkCyan",
      "Teal",
      "MediumTurquoise",
      "LightSeaGreen",
      "Turquoise",
      "Aquamarine",
      "MediumAquamarine",
      "MediumSpringGreen",
      "MintCream",
      "SpringGreen",
      "MediumSeaGreen",
      "SeaGreen",
      "Honeydew",
      "LightGreen",
      "PaleGreen",
      "DarkSeaGreen",
      "LimeGreen",
      "Color Name",
      "Lime",
      "ForestGreen",
      "Green",
      "DarkGreen",
      "Chartreuse",
      "LawnGreen",
      "GreenYellow",
      "DarkOliveGreen",
      "YellowGreen",
      "OliveDrab",
      "Beige",
      "LightGoldenrodYellow",
      "Ivory",
      "LightYellow",
      "Yellow",
      "Olive",
      "DarkKhaki",
      "LemonChiffon",
      "PaleGoldenrod",
      "Khaki",
      "Gold",
      "Cornsilk",
      "Goldenrod",
      "DarkGoldenrod",
      "FloralWhite",
      "OldLace",
      "Wheat",
      "Moccasin",
      "Orange",
      "PapayaWhip",
      "BlanchedAlmond",
      "NavajoWhite",
      "AntiqueWhite",
      "Tan",
      "BurlyWood",
      "Bisque",
      "DarkOrange",
      "Linen",
      "Peru",
      "PeachPuff",
      "SandyBrown",
      "Chocolate",
      "SaddleBrown",
      "Seashell",
      "Sienna",
      "LightSalmon",
      "Coral",
      "OrangeRed",
      "DarkSalmon",
      "Tomato",
      "MistyRose",
      "Salmon",
      "Snow",
      "LightCoral",
      "RosyBrown",
      "IndianRed",
      "Red",
      "Brown",
      "FireBrick",
      "DarkRed",
      "Maroon",
      "White",
      "WhiteSmoke",
      "Gainsboro",
      "LightGrey",
      "Silver",
      "DarkGray",
      "Gray",
      "DimGray",
      "Black"
    ]
  }
}

export default styles;
